### ISSUE TITLE
dylib not found

### ISSUE THREAD

**Issue by ziyiyin97** [lidongzh/FwiFlow.jl#3]
Hi Dongzhuo and Kailai,

Greetings! I am using your software FwiFlow.jl to reproduce your FWI tutorial in [https://lidongzh.github.io/FwiFlow.jl/dev/tutorials/fwi/](url) but meet the error as below.

I am on a Mac system and julia1.3 version. I ran the examples in ADCME tutorials and they are fine. I would really appreciate your help on this!

Also, do you have any example for FWI-Two Phase Flow Coupled Inversion, e.g. in your paper? I didn't find any in your tutorial webpage in [https://lidongzh.github.io/FwiFlow.jl/dev/](url).

Thank you! Hope you both enjoyed your Thanksgiving holiday.

Cheers,

Ziyi (Francis) Yin

`
julia> obs = compute_observation(sess, fwi, cp, cs, ρ, stf, shot_ids, gpu_id=0)
ERROR: File /Users/francisyin/.julia/packages/FwiFlow/ynbyK/deps/CustomOps/FWI/build/libFwiOp.dylib not found. If you intend to load a library by absolute path, try tf.load_op_library(filename).
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] load_library(::String) at /Users/francisyin/.julia/packages/ADCME/JzSON/src/extra.jl:1002
 [3] #load_op#247(::Missing, ::typeof(load_op), ::String, ::String) at /Users/francisyin/.julia/packages/ADCME/JzSON/src/extra.jl:141
 [4] load_op at /Users/francisyin/.julia/packages/ADCME/JzSON/src/extra.jl:136 [inlined]
 [5] fwi_obs_op(::PyCall.PyObject, ::PyCall.PyObject, ::PyCall.PyObject, ::PyCall.PyObject, ::Int64, ::PyCall.PyObject, ::String) at /Users/francisyin/.julia/packages/FwiFlow/ynbyK/src/Core.jl:51
 [6] #compute_observation#17(::Int64, ::typeof(compute_observation), ::PyCall.PyObject, ::FWI, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,1}, ::Array{Int64,1}) at /Users/francisyin/.julia/packages/FwiFlow/ynbyK/src/FWI.jl:115
 [7] (::FwiFlow.var"#kw##compute_observation")(::NamedTuple{(:gpu_id,),Tuple{Int64}}, ::typeof(compute_observation), ::PyCall.PyObject, ::FWI, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,1}, ::Array{Int64,1}) at ./none:0
 [8] top-level scope at REPL[34]:1
`

**Comment by ziyiyin97** [comment]
The building process generates a long message as well.

`julia> Pkg.build("FwiFlow")
  Building Conda ──→ `~/.julia/packages/Conda/x5ml4/deps/build.log`
  Building PyCall ─→ `~/.julia/packages/PyCall/BcTLp/deps/build.log`
  Building HDF5 ───→ `~/.julia/packages/HDF5/YX0jU/deps/build.log`
  Building Dierckx → `~/.julia/packages/Dierckx/ZTanR/deps/build.log`
  Building CMake ──→ `~/.julia/packages/CMake/ULbyn/deps/build.log`
  Building FFTW ───→ `~/.julia/packages/FFTW/DMUbN/deps/build.log`
  Building ADCME ──→ `~/.julia/packages/ADCME/JzSON/deps/build.log`
  Building FwiFlow → `~/.julia/packages/FwiFlow/ynbyK/deps/build.log`
┌ Error: Error building `FwiFlow`: 
│ WARNING: Method definition size(PyCall.PyObject) in module PyCall at /Users/francisyin/.julia/packages/PyCall/BcTLp/src/PyCall.jl:809 overwritten in module ADCME at /Users/francisyin/.julia/packages/ADCME/JzSON/src/variable.jl:213.
│   ** incremental compilation may be fatally broken for this module **
│ 
│ WARNING: Method definition length(PyCall.PyObject) in module PyCall at /Users/francisyin/.julia/packages/PyCall/BcTLp/src/PyCall.jl:808 overwritten in module ADCME at /Users/francisyin/.julia/packages/ADCME/JzSON/src/variable.jl:238.
│   ** incremental compilation may be fatally broken for this module **
│ 
│ WARNING: Method definition lastindex(PyCall.PyObject) in module PyCall at deprecated.jl:65 overwritten in module ADCME at /Users/francisyin/.julia/packages/ADCME/JzSON/src/variable.jl:425.
│   ** incremental compilation may be fatally broken for this module **
│ 
│ WARNING: Method definition *(PyCall.PyObject, PyCall.PyObject) in module PyCall at /Users/francisyin/.julia/packages/PyCall/BcTLp/src/pyoperators.jl:11 overwritten in module ADCME at /Users/francisyin/.julia/packages/ADCME/JzSON/src/ops.jl:103.
│   ** incremental compilation may be fatally broken for this module **
│ 
│ -- The C compiler identification is Clang 10.0.1
│ -- The CXX compiler identification is Clang 10.0.1
│ -- Check for working C compiler: /Users/francisyin/.julia/adcme/bin/clang
│ -- Check for working C compiler: /Users/francisyin/.julia/adcme/bin/clang -- broken
│ CMake Error at /Users/francisyin/.julia/packages/CMake/ULbyn/deps/downloads/cmake-3.15.3-Darwin-x86_64/CMake.app/Contents/share/cmake-3.15/Modules/CMakeTestCCompiler.cmake:60 (message):
│   The C compiler
│ 
│     "/Users/francisyin/.julia/adcme/bin/clang"
│ 
│   is not able to compile a simple test program.
│ 
│   It fails with the following output:
│ 
│     Change Dir: /Users/francisyin/.julia/packages/FwiFlow/ynbyK/deps/CustomOps/build/CMakeFiles/CMakeTmp
│     
│     Run Build Command(s):/Users/francisyin/.julia/adcme/bin/ninja cmTC_12eda && [1/2] Building C object CMakeFiles/cmTC_12eda.dir/testCCompiler.c.o
│     [2/2] Linking C executable cmTC_12eda
│     FAILED: cmTC_12eda 
│     : && /Users/francisyin/.julia/adcme/bin/clang -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -mmacosx-version-min=10.15 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/cmTC_12eda.dir/testCCompiler.c.o  -o cmTC_12eda   && :
│     ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/usr/lib/libSystem.tbd' for architecture x86_64
│     clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
│     ninja: build stopped: subcommand failed.
│     
│     
│ 
│   
│ 
│   CMake will not be able to correctly generate this project.
│ Call Stack (most recent call first):
│   CMakeLists.txt:2 (project)
│ 
│ 
│ -- Configuring incomplete, errors occurred!
│ See also "/Users/francisyin/.julia/packages/FwiFlow/ynbyK/deps/CustomOps/build/CMakeFiles/CMakeOutput.log".
│ See also "/Users/francisyin/.julia/packages/FwiFlow/ynbyK/deps/CustomOps/build/CMakeFiles/CMakeError.log".
│ ┌ Warning: Cannot load /Users/francisyin/.julia/packages/ADCME/JzSON/deps/CustomOps/build/libadcme.dylib. Please recompile the shared library by `ADCME.precompile()` for using custom operators.
│ └ @ ADCME ~/.julia/packages/ADCME/JzSON/src/ADCME.jl:95
│ [ Info: Install Boost
│ [ Info: Install AMGCL
│ [ Info: Build Custom Operators
│ ERROR: LoadError: failed process: Process(setenv(`/Users/francisyin/.julia/packages/CMake/ULbyn/deps/usr/bin/cmake -G Ninja -DCMAKE_MAKE_PROGRAM=/Users/francisyin/.julia/adcme/bin/ninja -DJULIA=/Applications/Julia-1.3.app/Contents/Resources/julia/bin/julia -DCMAKE_C_COMPILER=/Users/francisyin/.julia/adcme/bin/clang -DCMAKE_CXX_COMPILER=/Users/francisyin/.julia/adcme/bin/clang++ '' ..`,["XPC_FLAGS=0x0", "_CE_M=", "PATH=/opt/anaconda3/bin:/opt/anaconda3/condabin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin", "CONDA_PROMPT_MODIFIER=(base) ", "PWD=/Users/francisyin/Desktop/fwiflowoutput", "PYTHON=/opt/anaconda3/bin/python", "HDF5_USE_FILE_LOCKING=FALSE", "XPC_SERVICE_NAME=0", "TERM_PROGRAM=Apple_Terminal", "CONDA_PYTHON_EXE=/opt/anaconda3/bin/python"  …  "USER=francisyin", "CONDA_SHLVL=1", "MPLBACKEND=qt5agg", "CONDA_EXE=/opt/anaconda3/bin/conda", "TERM=xterm-256color", "HOME=/Users/francisyin", "TERM_PROGRAM_VERSION=433", "DEVITO_ARCH=gcc-8", "OPENBLAS_MAIN_FREE=1", "__KMP_REGISTERED_LIB_26944=0x133c31168-cafefb02-libomp.dylib"]), ProcessExited(1)) [1]
│ 
│ Stacktrace:
│  [1] pipeline_error at ./process.jl:525 [inlined]
│  [2] #run#565(::Bool, ::typeof(run), ::Cmd) at ./process.jl:440
│  [3] run at ./process.jl:438 [inlined]
│  [4] #cmake#244(::String, ::typeof(ADCME.cmake), ::String) at /Users/francisyin/.julia/packages/ADCME/JzSON/src/extra.jl:66
│  [5] cmake at /Users/francisyin/.julia/packages/ADCME/JzSON/src/extra.jl:51 [inlined] (repeats 2 times)
│  [6] top-level scope at /Users/francisyin/.julia/packages/FwiFlow/ynbyK/deps/build.jl:31
│  [7] include at ./boot.jl:328 [inlined]
│  [8] include_relative(::Module, ::String) at ./loading.jl:1105
│  [9] include(::Module, ::String) at ./Base.jl:31
│  [10] include(::String) at ./client.jl:424
│  [11] top-level scope at none:5
│ in expression starting at /Users/francisyin/.julia/packages/FwiFlow/ynbyK/deps/build.jl:31
│   Updating registry at `~/.julia/registries/SLIMregistryJL`
│   Updating git-repo `https://github.com/slimgroup/SLIMregistryJL.git`
 Resolving package versions...
│   Updating `/private/var/folders/5g/vpr8fq2s7d35x50d1tyggb8w0000gn/T/jl_oJYCJJ/Project.toml`
│  [no changes]
│   Updating `/private/var/folders/5g/vpr8fq2s7d35x50d1tyggb8w0000gn/T/jl_oJYCJJ/Manifest.toml`
│   [2a0f44e3] ~ Base64  [`@stdlib/Base64`] ⇒ 
│   [ade2ca70] ~ Dates  [`@stdlib/Dates`] ⇒ 
│   [8bb1440f] ~ DelimitedFiles  [`@stdlib/DelimitedFiles`] ⇒ 
│   [8ba89e20] ~ Distributed  [`@stdlib/Distributed`] ⇒ 
│   [b77e0a4c] ~ InteractiveUtils  [`@stdlib/InteractiveUtils`] ⇒ 
│   [76f85450] ~ LibGit2  [`@stdlib/LibGit2`] ⇒ 
│   [8f399da3] ~ Libdl  [`@stdlib/Libdl`] ⇒ 
│   [56ddb016] ~ Logging  [`@stdlib/Logging`] ⇒ 
│   [d6f4376e] ~ Markdown  [`@stdlib/Markdown`] ⇒ 
│   [a63ad114] ~ Mmap  [`@stdlib/Mmap`] ⇒ 
│   [44cfe95a] ~ Pkg  [`@stdlib/Pkg`] ⇒ 
│   [de0858da] ~ Printf  [`@stdlib/Printf`] ⇒ 
│   [3fa0cd96] ~ REPL  [`@stdlib/REPL`] ⇒ 
│   [ea8e919c] ~ SHA  [`@stdlib/SHA`] ⇒ 
│   [9e88b42a] ~ Serialization  [`@stdlib/Serialization`] ⇒ 
│   [1a1011a3] ~ SharedArrays  [`@stdlib/SharedArrays`] ⇒ 
│   [6462fe0b] ~ Sockets  [`@stdlib/Sockets`] ⇒ 
│   [2f01184e] ~ SparseArrays  [`@stdlib/SparseArrays`] ⇒ 
│   [10745b16] ~ Statistics  [`@stdlib/Statistics`] ⇒ 
│   [8dfed614] ~ Test  [`@stdlib/Test`] ⇒ 
│   [cf7118a7] ~ UUIDs  [`@stdlib/UUIDs`] ⇒ 
│   [4ec0a83e] ~ Unicode  [`@stdlib/Unicode`] ⇒ 
└ @ Pkg.Operations /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/Pkg/src/backwards_compatible_isolation.jl:649
false

`

**Comment by lidongzh** [comment]
> Hi Dongzhuo and Kailai,
> 
> Greetings! I am using your software FwiFlow.jl to reproduce your FWI tutorial in [https://lidongzh.github.io/FwiFlow.jl/dev/tutorials/fwi/](url) but meet the error as below.
> 
> I am on a Mac system and julia1.3 version. I ran the examples in ADCME tutorials and they are fine. I would really appreciate your help on this!
> 
> Also, do you have any example for FWI-Two Phase Flow Coupled Inversion, e.g. in your paper? I didn't find any in your tutorial webpage in [https://lidongzh.github.io/FwiFlow.jl/dev/](url).
> 
> Thank you! Hope you both enjoyed your Thanksgiving holiday.
> 
> Cheers,
> 
> Ziyi (Francis) Yin
> 
> `julia> obs = compute_observation(sess, fwi, cp, cs, ρ, stf, shot_ids, gpu_id=0) ERROR: File /Users/francisyin/.julia/packages/FwiFlow/ynbyK/deps/CustomOps/FWI/build/libFwiOp.dylib not found. If you intend to load a library by absolute path, try tf.load_op_library(filename). Stacktrace: [1] error(::String) at ./error.jl:33 [2] load_library(::String) at /Users/francisyin/.julia/packages/ADCME/JzSON/src/extra.jl:1002 [3] #load_op#247(::Missing, ::typeof(load_op), ::String, ::String) at /Users/francisyin/.julia/packages/ADCME/JzSON/src/extra.jl:141 [4] load_op at /Users/francisyin/.julia/packages/ADCME/JzSON/src/extra.jl:136 [inlined] [5] fwi_obs_op(::PyCall.PyObject, ::PyCall.PyObject, ::PyCall.PyObject, ::PyCall.PyObject, ::Int64, ::PyCall.PyObject, ::String) at /Users/francisyin/.julia/packages/FwiFlow/ynbyK/src/Core.jl:51 [6] #compute_observation#17(::Int64, ::typeof(compute_observation), ::PyCall.PyObject, ::FWI, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,1}, ::Array{Int64,1}) at /Users/francisyin/.julia/packages/FwiFlow/ynbyK/src/FWI.jl:115 [7] (::FwiFlow.var"#kw##compute_observation")(::NamedTuple{(:gpu_id,),Tuple{Int64}}, ::typeof(compute_observation), ::PyCall.PyObject, ::FWI, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,1}, ::Array{Int64,1}) at ./none:0 [8] top-level scope at REPL[34]:1`

Hi Ziyi, 

Thank you for your interest in our package! 

The FWI part has to run on GPU using CUDA, so it is necessary to test it on a Linux machine with NVIDIA GPUs. Also, our codes to reproduce the examples in the paper can be found here: https://github.com/lidongzh/TwoPhaseFlowFWI (see the MISC section in README.md) due to historical reasons. To run those code, you just need to change "using PyTensorFlow" to "using ADCME" manually. 

Sorry for the confusion. Hope this helps!

Best,
Dongzhuo

**Comment by lidongzh** [comment]
> Hi Dongzhuo and Kailai,
> 
> Greetings! I am using your software FwiFlow.jl to reproduce your FWI tutorial in [https://lidongzh.github.io/FwiFlow.jl/dev/tutorials/fwi/](url) but meet the error as below.
> 
> I am on a Mac system and julia1.3 version. I ran the examples in ADCME tutorials and they are fine. I would really appreciate your help on this!
> 
> Also, do you have any example for FWI-Two Phase Flow Coupled Inversion, e.g. in your paper? I didn't find any in your tutorial webpage in [https://lidongzh.github.io/FwiFlow.jl/dev/](url).
> 
> Thank you! Hope you both enjoyed your Thanksgiving holiday.
> 
> Cheers,
> 
> Ziyi (Francis) Yin
> 
> `julia> obs = compute_observation(sess, fwi, cp, cs, ρ, stf, shot_ids, gpu_id=0) ERROR: File /Users/francisyin/.julia/packages/FwiFlow/ynbyK/deps/CustomOps/FWI/build/libFwiOp.dylib not found. If you intend to load a library by absolute path, try tf.load_op_library(filename). Stacktrace: [1] error(::String) at ./error.jl:33 [2] load_library(::String) at /Users/francisyin/.julia/packages/ADCME/JzSON/src/extra.jl:1002 [3] #load_op#247(::Missing, ::typeof(load_op), ::String, ::String) at /Users/francisyin/.julia/packages/ADCME/JzSON/src/extra.jl:141 [4] load_op at /Users/francisyin/.julia/packages/ADCME/JzSON/src/extra.jl:136 [inlined] [5] fwi_obs_op(::PyCall.PyObject, ::PyCall.PyObject, ::PyCall.PyObject, ::PyCall.PyObject, ::Int64, ::PyCall.PyObject, ::String) at /Users/francisyin/.julia/packages/FwiFlow/ynbyK/src/Core.jl:51 [6] #compute_observation#17(::Int64, ::typeof(compute_observation), ::PyCall.PyObject, ::FWI, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,1}, ::Array{Int64,1}) at /Users/francisyin/.julia/packages/FwiFlow/ynbyK/src/FWI.jl:115 [7] (::FwiFlow.var"#kw##compute_observation")(::NamedTuple{(:gpu_id,),Tuple{Int64}}, ::typeof(compute_observation), ::PyCall.PyObject, ::FWI, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,1}, ::Array{Int64,1}) at ./none:0 [8] top-level scope at REPL[34]:1`

**Comment by ziyiyin97** [comment]
Thanks for your help Dongzhuo! Closing
